#!/usr/bin/env bash
source ../conf.sh

case $1 in
    start | 1)
        start zookeeper-dev
        echo "启动 zookeeper-dev docker服务"
        ;;
    stop | 2)
        stop zookeeper-dev
        echo "关闭 zookeeper-dev docker服务"
        ;;
    3)
        exec_ zookeeper-dev $2
        ;;
    4)
        echo "进入 zookeeper-dev docker服务"
        exec_in zookeeper-dev
        ;;
    5)
        clear_container zookeeper-dev
        echo "清理 zookeeper-dev docker服务"
        ;;
    6)
        clear_all_container
        echo "清理所有 docker服务"
        ;;

    *)
        echo -e "请输入参数:\n"
        echo "启动zookeeper-dev服务: 1"
        echo "关闭zookeeper-dev服务: 2"
        echo "进入容器zookeeper-dev服务: 3 ls /"
        echo "进入容器zookeeper-dev服务: 4"
        echo "清理容器zookeeper-dev服务: 5"
        echo "清理所有容器zookeeper-dev服务: 6"
        echo -e "-n"
        echo -e "例如:\n"
        echo "zookeeper-dev-toolkit 1                    # 启动zookeeper-dev容器服务"
        echo "zookeeper-dev-toolkit 2                    # 关闭zookeeper-dev容器服务"
        echo "zookeeper-dev-toolkit 3 shell命令  # 进入 zookeeper-dev容器 并执行shell命令"
        echo "zookeeper-dev-toolkit 4                    # 进入容器zookeeper-dev服务: 4"
        ;;
esac
