actions:
  1:
    action: delete_indices
    description: "delete expire index"
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: yaobili-
    - filtertype: age
      source: field_stats
      direction: older
      unit: days
      unit_count: 7
      field: '@timestamp'
      stats_result: min_value